# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.tableView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_2.addWidget(self.tableView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.coverLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.coverLabel.setMinimumSize(QtCore.QSize(200, 200))
        self.coverLabel.setMaximumSize(QtCore.QSize(200, 200))
        self.coverLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.coverLabel.setObjectName("coverLabel")
        self.verticalLayout.addWidget(self.coverLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addFilesButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addFilesButton.setObjectName("addFilesButton")
        self.horizontalLayout.addWidget(self.addFilesButton)
        self.addFolderButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addFolderButton.setObjectName("addFolderButton")
        self.horizontalLayout.addWidget(self.addFolderButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.logOutput = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.logOutput.setMaximumSize(QtCore.QSize(16777215, 100))
        self.logOutput.setReadOnly(True)
        self.logOutput.setObjectName("logOutput")
        self.verticalLayout_2.addWidget(self.logOutput)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.progressBar = QtWidgets.QProgressBar(parent=self.statusbar)
        self.progressBar.setGeometry(QtCore.QRect(10, 0, 150, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Media Tagger Pro"))
        self.coverLabel.setText(_translate("MainWindow", "Capa do Álbum"))
        self.addFilesButton.setText(_translate("MainWindow", "Adicionar Arquivos"))
        self.addFolderButton.setText(_translate("MainWindow", "Adicionar Pasta"))
        self.saveButton.setText(_translate("MainWindow", "Salvar Alterações"))
